#!/usr/bin/perl -w

use BOSS::Config;
use KBS2::ImportExport;
use KBS2::Util;
use PerlLib::SwissArmyKnife;

$specification = q(
	-i <type>		Input type
	-o <type>		Output type

	-f <file>...		Files to Convert

	-l			List possible input/output types

	-g			Try to guess input type

	-d			Debug
);

my $config =
  BOSS::Config->new
  (Spec => $specification);
my $conf = $config->CLIConfig;
# $UNIVERSAL::systemdir = "/var/lib/myfrdcsa/codebases/minor/system";

my $debug = exists $conf->{'-d'} ? 1 : 0;
my $importexport = KBS2::ImportExport->new(Debug => $debug);
die "ERROR: You must specify files to process with -f" unless defined $conf->{'-f'};

foreach my $file (@{$conf->{'-f'}}) {
  if (-f $file) {
    my $input = read_file($file);
    my $inputtype;
    my $outputtype;
    if ($conf->{'-i'}) {
      $inputtype = $conf->{'-i'};
    } elsif ($conf->{'-g'}) {
      NotYetImplemented();
      die;
    } else {
      die "ERROR: you must specify input type with -i or to guess with -g";
    }
    if ($conf->{'-o'}) {
      $outputtype = $conf->{'-o'};
    } else {
      die "ERROR: you must specify output type with -o";
    }
    my $res1 = $importexport->Convert
      (
       Input => $input,
       InputType => $inputtype,
       OutputType => $outputtype,
      );
    if ($res1->{Success}) {
      print $res1->{Output}."\n";
    } else {
      die Dumper($res1);
    }
  }
}
